---
# Items that apply to ALL profiles:

eureka:
  instance:
    hostname: 198.13.51.15
  client:
    serviceUrl:
      defaultZone: http://198.13.51.15:8001/eureka/

---
spring:
  rabbitmq:
    host: 198.13.51.15
    port: 5672
    username: admin
    password: admin
    addresses: amqp://198.13.51.15:5672/
  zipkin:
    base-url: http://198.13.51.15:9411/
