
---
spring:
  rabbitmq:
    host: localhost
    # 10.133.33.126
    port: 5672
    username: admin
    password: admin
    addresses: amqp://localhost:5672/
  zipkin:
    base-url:  http://localhost:9411/

