---
# Items that apply to ALL profiles:
eureka:
  instance:
    hostname: 198.13.51.15
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8001/eureka/

---
spring:
  rabbitmq:
    host: 198.13.51.15
    port: 5672
    username: admin
    password: admin
    addresses: amqp://${spring.rabbitmq.host}:${spring.rabbitmq.port}/
  zipkin:
    base-url: http://${spring.rabbitmq.host}:9411/
