---
# Items that apply to ALL profiles:
host: 198.13.51.15

eureka:
  instance:
    hostname: ${host}
  client:
    serviceUrl:
      defaultZone: http://${host}:8001/eureka/

---
host: 198.13.51.15

spring:
  rabbitmq:
    host: ${host}
    port: 5672
    username: admin
    password: admin
    addresses: amqp://${host}:${spring.rabbitmq.port}/
  zipkin:
    base-url: http://${host}:9411/
