# Dev Config
---
spring:
  data:
    neo4j:
      uri: http://localhost:7474/
      repositories:
        enabled: true
      username: neo4j
      password: neo4spring_cloud

---
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    addresses: amqp://localhost:5672/
  zipkin:
    base-url:  http://localhost:9411/
