
---
host: 198.13.51.15

spring:
  rabbitmq:
    host: ${host}
    port: 5672
    username: remote
    password: remote
    addresses: ${host}:5672
  zipkin:
    base-url: http://${host}:9411/

# set logging level because of bug in swagger-models dependency
logging:
  level:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: ERROR


##############################################################
################## Exposing Web-Endpoints ####################
##############################################################
---
management:
  endpoints:
    web:
      exposure:
        include: "*"

