
---
spring:
  rabbitmq:
    host: 198.13.51.15
    port: 5672
    username: remote
    password: remote
    addresses: 198.13.51.15:5672
  zipkin:
    base-url: http://198.13.51.15:9411/

# set logging level because of bug in swagger-models dependency
logging:
  level:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: ERROR


##############################################################
################## Exposing Web-Endpoints ####################
##############################################################
---
management:
  endpoints:
    web:
      exposure:
        include: "*"

