# Dev Config
---
spring:
  data:
    neo4j:
      uri: http://10.133.33.126:7474/
      repositories:
        enabled: true
      username: neo4j
      password: neo4spring_cloud

---
spring:
  rabbitmq:
    host: 10.133.33.126
    port: 5672
    username: admin
    password: admin
    addresses: amqp://10.133.33.126:5672/
  zipkin:
    base-url:  http://10.133.33.126:9411/
