# Live Config
---
spring:
  hateoas:
    use-hal-as-default-json-me
  data:
    neo4j:
      uri: http://localhost:7474
      repositories:
        enabled: true
      username: neo4j
      password: neo4spring_cloud


