---
# Items that apply to ALL profiles:
eureka:
  instance:
    hostname: 10.133.33.126
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8001/eureka/
      
---
####################### Hystrix Configuration #######################
management:
  endpoints:
    web:
      exposure:
        include: health,info,hystrix.stream,bus-refresh
      base-path: /
    hystrix:
      stream:
        enabled: true 

---
spring:
  rabbitmq:
    host: 10.133.33.126
    port: 5672
    username: remote
    password: remote
    addresses: 10.133.33.126:5672
  zipkin:
    base-url:  http://10.133.33.126:9411/

---
#set logging level because of bug in swagger-models dependency
logging:
  level:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: ERROR
            
---
####################### Cron-Job Every 2mins every day #######################
purge:
  cron:
    expression: 0 0/2 * * * ?
    