
---
spring:
  rabbitmq:
    host: 10.133.33.126
    port: 5672
    username: remote
    password: remote
    addresses: amqps://10.133.33.126:5672
  zipkin:
    base-url:  http://10.133.33.126:9411/
