# Live Config
---
spring:
  main:
    allow-bean-definition-overriding: true
  data:
    rest:
      basePath: /api/v1
    neo4j:
      uri: http://${spring.rabbitmq.host}:7474/
      repositories:
        enabled: true
      username: neo4j
      password: neo4spring_cloud

---
spring:
  rabbitmq:
    host: 198.13.51.15
    port: 5672
    username: admin
    password: admin
    addresses: amqp://${spring.rabbitmq.host}:5672/
  zipkin:
    base-url:  http://${spring.rabbitmq.host}:9411/
