# Live Config
---
spring:
  data:
    neo4j:
      uri: http://192.168.0.3:7474
      repositories:
        enabled: true
      username: neo4j
      password: neo4spring_cloud

---
spring:
  rabbitmq:
    host: 192.168.0.3
    port: 5672
    username: admin
    password: admin
    addresses: amqp://192.168.0.3:5672/
  zipkin:
    base-url:  http://192.168.0.3:9411/
