---
zuul:
  prefix: /api
  ignored-services: leader-data, config-server
  routes:
    leaderboard:
      path: /game-match
    game:
      path: /game-engine

---
host: 198.13.51.15

spring:
  rabbitmq:
    host: ${host}
    port: 5672
    username: admin
    password: admin
    addresses: amqp://${host}:5672/
  zipkin:
    base-url: http://${host}:9411/
    discovery-client-enabled: true

# Ports:
#  sciroc ------- 8000
#  Eureka: ------ 8001
#  Config: ------ 8002
#  leader-data -- 8003
#  leaderboard -- 8004
#  zuul-gateway - 8005
#  game --------- 8006
#  rabbit-mq ---- 192.168.0.3:5672 (On a different machine under the same network)
#  zipkin ------- 192.168.0.3:9411 (On a different machine under the same network)
